module Layout exposing (footerView, headerView)

import Html exposing (..)
import Html.Attributes exposing (..)
import Html.Events exposing (..)
import Routing


headerView : () -> Html msg
headerView _ =
    header []
        [ nav [ class "navbar navbar-expand-lg navbar-dark bg-dark" ]
            [ div [ class "container" ]
                [ a [ class "navbar-brand", href "/" ]
                    [ i [ class "bi bi-github", style "margin-right" "10px", style "font-size" "1.43rem" ]
                        []
                    , text "Github Finder"
                    ]
                , button [ class "navbar-toggler", type_ "button" ] [ span [ class "navbar-toggler-icon" ] [] ]
                , ul [ class "collapse navbar-collapse navbar-nav justify-content-end" ]
                    [ li [ class "nav-item" ]
                        [ a [ attribute "aria-current" "page", class "nav-link active", Routing.href Routing.Home ]
                            [ text "Home" ]
                        ]
                    , li [ class "nav-item" ]
                        [ a [ class "nav-link", href "#" ]
                            [ text "Favorites" ]
                        ]
                    , li [ class "nav-item" ]
                        [ a [ class "nav-link", Routing.href (Routing.ProfileDetail "test") ]
                            [ text "Profiles" ]
                        ]
                    , li [ class "nav-item" ]
                        [ a [ class "nav-link", href "#" ]
                            [ text "Repositories" ]
                        ]
                    ]
                ]
            ]
        ]


footerView : () -> Html msg
footerView _ =
    footer [ class "page-footer font-small indigo" ]
        [ div [ class "container" ]
            [ div [ class "row text-center d-flex justify-content-center pt-5 mb-3" ]
                [ div [ class "col-md-2 mb-3" ]
                    [ h6 [ class "text-uppercase font-weight-bold" ]
                        [ a [ href "#!" ]
                            [ text "About us" ]
                        ]
                    ]
                , text "          "
                , div [ class "col-md-2 mb-3" ]
                    [ h6 [ class "text-uppercase font-weight-bold" ]
                        [ a [ href "#!" ]
                            [ text "Products" ]
                        ]
                    ]
                , text "          "
                , div [ class "col-md-2 mb-3" ]
                    [ h6 [ class "text-uppercase font-weight-bold" ]
                        [ a [ href "#!" ]
                            [ text "Awards" ]
                        ]
                    ]
                , text "          "
                , div [ class "col-md-2 mb-3" ]
                    [ h6 [ class "text-uppercase font-weight-bold" ]
                        [ a [ href "#!" ]
                            [ text "Help" ]
                        ]
                    ]
                , text "          "
                , div [ class "col-md-2 mb-3" ]
                    [ h6 [ class "text-uppercase font-weight-bold" ]
                        [ a [ href "#!" ]
                            [ text "Contact" ]
                        ]
                    ]
                , text "        "
                ]
            , hr [ class "rgba-white-light", attribute "style" "margin: 0 15%;" ]
                []
            , div [ class "row d-flex text-center justify-content-center mb-md-0 mb-4" ]
                [ div [ class "col-md-8 col-12 mt-5" ]
                    [ p [ attribute "style" "line-height: 1.7rem" ]
                        [ text "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium              doloremque laudantium, totam rem aperiam,              eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo              enim              ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur." ]
                    ]
                , text "        "
                ]
            , hr [ class "clearfix d-md-none rgba-white-light", attribute "style" "margin: 10% 15% 5%;" ]
                []
            , div [ class "row pb-3" ]
                [ div [ class "col-md-12" ]
                    [ div [ class "mb-5 flex-center" ]
                        [ a [ class "fb-ic" ]
                            [ i [ class "fab fa-facebook-f fa-lg white-text mr-4" ]
                                []
                            ]
                        , a [ class "tw-ic" ]
                            [ i [ class "fab fa-twitter fa-lg white-text mr-4" ]
                                []
                            ]
                        , a [ class "gplus-ic" ]
                            [ i [ class "fab fa-google-plus-g fa-lg white-text mr-4" ]
                                []
                            ]
                        , a [ class "li-ic" ]
                            [ i [ class "fab fa-linkedin-in fa-lg white-text mr-4" ]
                                []
                            ]
                        , a [ class "ins-ic" ]
                            [ i [ class "fab fa-instagram fa-lg white-text mr-4" ]
                                []
                            ]
                        , a [ class "pin-ic" ]
                            [ i [ class "fab fa-pinterest fa-lg white-text" ]
                                []
                            ]
                        ]
                    ]
                , text "        "
                ]
            , text "      "
            ]
        , text "      "
        , div [ class "footer-copyright text-center py-3" ]
            [ text "© 2020 Copyright:        "
            , a [ href "/" ]
                [ text "MDBootstrap.com" ]
            ]
        , text "    "
        ]
